name: note-processor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: CI
      working-directory: ./note-processor
      run: npm ci
    - name: Build
      working-directory: ./note-processor
      run: npm run build
    - name: Test
      working-directory: ./note-processor
      run: npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: .build
        path: |
          ./note-processor/.build
          !./note-processor/.build/**/*.d.ts

  build_push_docker:
    runs-on: ubuntu-latest
    needs: build_test_node

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Build Image
      working-directory: ./note-processor
      run: ./ci/build.sh latest
